- builder.sh
This enables people to use the username and password for login to docker which sometimes causes errors with uploading.
> add username and password options to docker login

- builder.sh
Currently it's not possible because the actual value is not shifted after assigning and therefore the script breaks.
> allow to set docker user and password

- builder.sh
I added a new builder parameter, which allows a custom tag to be set as cache source.
For me it helps me to get around issues with the default `latest` tag, since some services assume this tag to be the real release instead of versioned images.
> Add commandline option for a custom cache tag

- .github/workflows/test.yml
- README.md
- action.yml
- builder.sh
This PR makes this repository become a GitHub action so other repositories can use the builder to test and publish their stuff.
As an example, I have tested my fork of this, and a fork of the supervisor repo and this are the results:
- [action file](https://github.com/ludeeus/supervisor/blob/action/.github/workflows/build.yml)
- [action log](https://github.com/ludeeus/supervisor/actions/runs/320443048)
- [dockerhub](https://hub.docker.com/layers/ludeeus/amd64-hassio-supervisor/52216a6c198fe1596c20f737ca388aa5174fc840/images/sha256-594792f9b2db9ec39493c32dd1f8159c1b8a0cc4b0bc20f56fac39e5c43c64f9?context=repo)
In addition to this, I've changed the `builder.sh` file so it now exits after 3 attempts resulting in a failed action.
> Create GitHub action

- README.md
- action.yml
- Removes the `version` key for `with`
- Uses the requested action version as the builder version, if `master` it uses the `latest` builder
So with this change:
- `uses: home-assistant/builder@master` will use `homeassistant/amd64-builder:latest` 
- `uses: home-assistant/builder@2020.10.0` will use `homeassistant/amd64-builder:2020.10.0`
> Change version handling

- .github/workflows/hadolint.yml
- .github/workflows/shellcheck.yml
- README.md
Brings the action to the top, and adds the arguments.
Should we wrap it in `<details>`?
Example: 
<details>
<summary>Expand to see all the arguments</summary>
```
Options:
-h, --help
Display this help and exit.
Repository / Data
-r, --repository <REPOSITORY>
Set git repository to load data from.
-b, --branch <BRANCH>
Set git branch for repository.
-t, --target <PATH_TO_BUILD>
Set local folder or path inside repository for build.
Version/Image handling
-v, --version <VERSION>
Overwrite version/tag of build.
-i, --image <IMAGE_NAME>
Overwrite image name of build / support {arch}.
--release <VERSION>
Additional version information like for base images.
--release-tag
Use this as main tag.
Architecture
--armhf
Build for arm v6.
--armv7
Build for arm v7.
--amd64
Build for intel/amd 64bit. …
```
> Restructure README

- README.md
- builder.sh
On the use of the new cache tag parameter I noticed that the parameter were not shifted. This PR corrects this.
> Fix custom cache tag parameter retrieval

- .github/workflows/publish.yml
- .github/workflows/test.yml
Since the action is pulling down lastest, we are actually not testing changes to the Dockerfile of the builder script.
This will (for PR's), build the builder using latest, which will produce a new builder (with latest), that will be used to do the test build,
> Build before test

- builder.sh
This PR is supplemental to the `operating-system` PR https://github.com/home-assistant/operating-system/pull/926, which adds support for the Odroid C4 SBC.
> Support Odroid C4 SBC

- action.yml
Current output:
```
REPOSITORY                                           TAG                 IMAGE ID            CREATED             SIZE
homeassistant/amd64-builder                          latest              e3cebba27d39        1 second ago        716MB
homeassistant/amd64-base-ubuntu                      18.04               5280d4156ab4        18 hours ago        85.3MB
homeassistant/amd64-builder                          <none>              fad53788139a        24 hours ago        710MB
node                                                 10                  56387899b840        2 weeks ago         911MB
node                                                 12                  1f560ce4ce7e        2 weeks ago         918MB
buildpack-deps                                       stretch …
```
> Filter output of docker images

- builder.sh
Allow to set the build version for add-ons via the --version or -v parameter.
Using the GitHub actions, I want to be able to use different actions for different purposes, and different results. For example:
- Action 1 builds and uploads the addon release docker files. This is currently possible
- Action 2 builds a dev/edge docker image that is using a specific tag/version which is different to the version of the stable addon, and which is not latest. 
1. Don't set a local version variable when building an addon
2. Read the version from config.json only when global version variable is empty (e.g. when not set, default)
```
- name: Publish
uses: home-assistant/builder@master
with:
args: |
--all \
--target /data \
--version test \
--docker-hub userspace-name
```
> Allow --version to overwrite addon version

- builder.sh
The Intel NUC machine runs on most UEFI capable x86-64 machines today.
Lets start a new machine generic-x86-64 which will replace intel-nuc
over time.
> Add support for generic-x86-64 machine

- builder.sh
This is for the transition time
> Modify handling of crossbuild

- builder.sh
The trap method calls `clean_crosscompile`, which has been removed from the builder.
Fixes #86
> Fix call to removed function in trap

- builder.sh
Add Khadas VIM3 machine, based on a Amlogic A311D with Cortex-A53/A73.
> Add support for khadas-vim3 machine

- builder.sh
The remote repository needs to be fetched before the configuration files can be read.
For example:
```
docker run --privileged homeassistant/amd64-builder -r https://github.com/home-assistant/core  --amd64 --generic 1.0
```
This would fail as the build.yaml file is not accessible before the home-assistant/core is checked-out.
> fetch repository before copying build_config

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
[Shellcheck package](https://pkgs.alpinelinux.org/packages?name=shellcheck&branch=v3.13) is only available for alpine with `x86_64` architecture. Devcontainer simply fails to start on `aarch64` or any other architecture. It's also not really needed as the shellcheck extension works fine without it. Removing it from the devcontainer Dockerfile.
Also since that was the only customization in the devcontainer Dockerfile, just removed the Dockerfile entirely and set it to use the ms image directly.
> Remove shellcheck package from devcontainer

- builder.sh
Not a bug but figured it could help us get to the bottom of issues like [this](https://github.com/home-assistant/plugin-dns/runs/5387152880?check_suite_focus=true)
> Include platform in CI output

- Dockerfile
- README.md
- builder.sh
This starts using `buildx` for the build command
This is needed for <https://github.com/home-assistant/plugin-observer/pull/89>
> Use buildx when building images

- builder.sh
With this change you can now set the image to use other docker registries, not just dockerhub.
I.e. now using `image: gchr.io/me/addon` will work.
> Better host support

- action.yml
Fix get version (last part from repository path) to correct behavior in case of different path lengths.
> Fix get branch (last part from path) to correct behavior in case of different path lengths

- README.md
The commands currently documented download an old version of the builder which lead to errors during build since the images on Docker Hub still used cas:
```
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 3.33.152.147:443: i/o timeout"
```
> Document new builder location on ghcr.io

- builder.sh
Image builds failed on i386 because the builder tried to install the x86_64 package which doesn't exist on i386 https://github.com/home-assistant/core/actions/runs/7392726377/job/20111619276 because python saw the arch as x86_64 instead of i386
The wheel builder is able to handle this case so the goal is to match https://github.com/home-assistant/wheels/blob/6a18828c159faf31114eb1bf4b2ffae30d7fbc66/rootfs/bin/run-builder.sh#L5
> Fix i386 builds reporting x86_64 in the build process

- action.yml
- build.yaml
Move to the default cosign version what the latest cosign-installer would provide by default. Still explicitly select the version to make sure it stays in sync with the version installed in the builder.
> Use default cosign version v2.2.3 provided by cosign-installer action

- build.yaml
The current version of cosign deployed in the latest builder doesn't work with the currently deployed TUF Trust Root on the sigstore servers (see also https://blog.sigstore.dev/tuf-root-update/).
Remove the cosign identity information to temporarily disable signature verification. This allows to build a new release with a newer cosign.
> Disable cosign signature verification

- action.yml
Since we can't sign the current builder, we also need to disable verification of it's signature. This avoids another chicken-egg-problem.
> Disable cosign verification by default

- action.yml
- build.yaml
With 2024.03.4 we have a working and signed version of the builder again. We can reenable cosign verification in the builder as well as in the builder CI.
> Reenable cosign verification

- .github/workflows/publish.yml
This resolves a couple of warnings in GitHub Actions on release.
> Update get-tag GitHub Action to v2.1.3

- builder.sh
I've discovered that the add-on builder doesn't apply the labels configured in the add-on's `build.(yaml|json)` file.
You can see this in action in the example add-on [repo's packages](https://github.com/home-assistant/addons-example/pkgs/container/amd64-addon-example/39826407?tag=1.2.0) as the "About this version" section hasn't been auto-populated:
... and the manifest shows the labels haven't been applied either:
This PR rectifies this by parsing the `build.(yaml|json)` file for the labels in `build_addon()` in the same way as the other build functions do.
> Apply labels from add-on `build.(yaml|json)` when building add-on

- builder.sh
Currently, when build information are missing the following error is printed:
```
[15:41:46] ERROR: amd64 not supported for this build
```
This is rather misleading. Print an error when the build information are not available.
> Inform if build information are not available

- Dockerfile
With the Alpine 3.20 upgrade git no longer by default trust git repositories. This leads to a warning by Dockers BuildKit:
WARNING: current commit information was not captured by the build: failed to read current commit information with git rev-parse --is-inside-work-tree
Avoid this warning by trusting all git repositories like before the Alpine 3.20 upgrade.
It probably would be better if we can simply trust only the passed data directory, but the git repository might be higher up then the passed path. Also the data directory could be something other than /data.
> Trust git repositories in builder

- builder.sh
Instead of using the image name and tag, use the image name and the manifest sha256. This allows to verify the image sha256 in logs etc. and gets rid of the following warning from cosign:
```
WARNING: Image reference ghcr.io/home-assistant/amd64-builder:dev uses a tag, not a digest, to identify the image to sign.
```
> Use manifest digest for signing

- .github/workflows/test.yml
- action.yml
Correctly pull the image by default.
The if expression was really wrong. This hasn't been noticed in #214 since the comparison with true == "true" indeed lead to the step not being executed. The GitHub Action syntax doesn't support boolean inputs. Make this explicit using strings.
> Make sure builder image is pulled by default

- .devcontainer/devcontainer.json
vs code now need 3.16+ Alpine linux as container image. the default image version need to be updated
> bug fix issue 209 default Alpine version 3.13->3.16

- action.yml
It seems that QEMU and Address Space Layout Randomization do not work well toghether currently. Linux kernel security hardening efforts which make ASLR more random seem to cause SEGFAULTs randomly when building things for aarch64.
It seems that the QEMU for aarch64 made assumptions about how the memory layout is laid out, and/or has bugs in the implementation which are exarbated by the new ASLR scheme. In any case, disabling ASLR during build time avvoids hitting the QEMU bugs.
> Disable ASLR to work around QEMU aarch64 issues

- action.yml
With this we can use the home-assistant/builder action also on the new arm runners by passing `image: aarch64` when running on `ubuntu-24.04-arm` - example https://github.com/mib1185/ha-addon-syslog/pull/19
Maybe we could also auto-detect the arch of the runner, but I didn't find a reliable way to determine the runners architecture.
> Make builder image arch selectible

- builder.sh
Currently the instructions and default base image still point to Docker Hub. The respective images are not up-to-date on Docker Hub. Switch to use the GitHub container registry instead.
> Use ghcr.io as default registry for base image/instructions

- README.md
- builder.sh
When using the builder for local development builds, Cosign signing adds unnecessary complexity. However, if the images are not signed, the cache can't be used because verifying the image fails. Add new flag to explicitly disable verification of the signature which can be used for these scenarios.
> Add `--no-cosign-verify` flag to disable Cosign signature verification
